### ISSUE TITLE
Control Interface Not Working 

### ISSUE THREAD

**Issue by iddogefen** [AR-Eye-Tracking-Toolkit/ARETT#1]
Hi,

I downloaded ARETT Toolkit. I started the startup on my computer, but when I try to access the Control Interface link in the Unity Editor there was no connection. I tried to enter the following link: http://127.0.0.1:8080/.
I also tried "My IP:8080/".
Am I doing something wrong?

When I clicked on the link of the index I got to the page of the software but it was written that there is no connection to the device.

I am using Unity 2021.3.13f1 and MRTK 2.72

Thanks!

Iddo
![ARETT1](https://user-images.githubusercontent.com/88090385/127318011-c16e25be-876a-4162-812e-b717256c189b.jpg)
![ARETT2](https://user-images.githubusercontent.com/88090385/127318265-fc017814-5e86-4663-9055-b245cf97a8a9.jpg)
![ARETT3](https://user-images.githubusercontent.com/88090385/127318653-98968ed0-d37b-4046-9593-916a4e181c5a.jpg)

**Comment by sekapp** [comment]
Hi Iddo,

did you start the application in the Editor using the play button before trying to access the interface in the browser?
For the Interface to work the application must be running and then you must access the IP address of the device the application is running on. When running in the editor the IP is localhost/127.0.0.1, when running on the HoloLens 2 you must access the IP address of the device.

As you changed the "Listener Base URI" to `http://127.0.0.1:8080` instead of the default `http://*:8080` (see [here](https://github.com/AR-Eye-Tracking-Toolkit/ARETT/blob/master/Scripts/WebServer.cs#L46)) you can access the web server only using 127.0.0.1 and not e.g. when running on the device. However, this might also completely break access (sadly I'm unable to test this right now).
The address set in Unity should stay the default for the interface to work and should only be changed if necessary.

At your last screenshot you are opening the web interface html as file. This does not work as the interface only works when accessed using the web server of the running application.

So please try the following:
1. Reset the "Listener Base URI" to the default value in Unity
2. Start the application in Unity using the "Play" Button/using "Play mode"
3. Try accessing the web interface on the same PC as the Unity Editor is running under http://127.0.0.1:8080/

If you want to access and control ARETT running on a device, you must access the interface using the IP address of the device.

Best regards,
Sebastian Kapp

**Comment by iddogefen** [comment]
It worked! Thank you!

I think my initial mistake was that I was trying to get in control interface when Unity was not in "play mode". After I played with the settings it did not work at all, but I just tried again in a new project in Unity according to your instructions and it finally worked.

It looks like an amazing tool and can not wait to try to use it in research. Thanks for the development and the help!

Iddo
