### ISSUE TITLE
Resuming App after launching Eye Calibration

### ISSUE THREAD

**Issue by Mattiademasi** [AR-Eye-Tracking-Toolkit/ARETT#10]
Hi Sebastian,

When launching the Eye calibration via Control Interface, the application does not resume automatically but I have to click on the white board to go back to my immersive app.

Best regards,
Mattia Demasi

**Comment by sekapp** [comment]
Hi Mattia,

sadly this behavior is due to the calibration being a separate application which is launched. This suspends all other applications (see [wiki](https://github.com/AR-Eye-Tracking-Toolkit/ARETT/wiki/Control-Interface#launch-et-calibration)).
I don't know a way to automatically resume or restart the previous application after successfull calibration. However, if you do know a way to make this work I'm happy to accept e.g. pull requests.

Best regards
Sebastian Kapp
